services:
  postgres:
    image: postgres:latest
    container_name: authentication-postgres
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./data:/var/lib/postgresql/data
    networks:
      - my_network

networks:
  my_network:
    external: true
